name: Deploy static site to GitHub Pages

on:
  push:
    branches: [master]  # Make sure you push to 'master' branch, or change this if you're using 'main'

permissions:
  contents: write       # Required to push to gh-pages branch
  id-token: write       # Required for OpenID Connect token

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site  # Make sure this folder exists and contains index.html

      - name: Debug OIDC token injection
        run: |
          echo "Checking for injected GitHub OIDC environment variables..."
          env | grep ACTIONS_ID_TOKEN || echo "OIDC environment variables are NOT present!"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
